database:
  type: "sqlite"
  mysql:
    address: ""
    database: ""
    username: ""
    password: ""
  sqlite:
    file: "database.db"

initial-time:
  MENSAL: -1
  TRIMESTRAL: -1

reset-time:
  MENSAL: -1
  TRIMESTRAL: -1

discord-webhook-link: ""

view:
  defaultEventHead: "/texture/6d0f4061bfb767a7f922a6ca7176f7a9b20709bd0512696beb15ea6fa98ca55c"
  filterColor: "&b"
  clanRankingInfo: " &f%time%: &e%pontos% pontos &6(#%position%)"
  mainInventoryName: "Saint Ligas"
  leagueHistoric:
    material: "/texture/ab527a18dec3d6dac532f5555b9119c31b7a8397b8a06d249d0eb39241c5485f"
    name: "&aHistórico de Eventos"
    lore:
      - '&7Veja os eventos anteriores que'
      - '&7ocorream na liga e quantos'
      - '&7pontos foram fornecidos'
      - ''
      - '&aClique para ver o histórico!'
  rewards:
    material: "/texture/a2629f2682dcee30f5855b1e5427cc4bee73d18a276fafc520d693b40ca81b22"
    name: "&aRecompensas"
    lore:
      - '&7Veja as recompensas que o clan'
      - '&7pode receber ao final da liga'
      - ''
      - '&aClique para ver as recompensas!'
  leagueRank:
    material: "/texture/e34a592a79397a8df3997c43091694fc2fb76c883a76cce89f0227e5c9f1dfe"
    name: "&aRanking da liga"
    lore:
      - '&7Veja quais clans estão liderando'
      - '&7a liga atualmente'
      - ''
      - '&aClique para ver o ranking da liga!'
  profile:
    name: "&aSeu Perfil"
    noClanLore:
      - '&fSeus pontos: &e%pontos%'
      - '&fSeu clan: &cNenhum'
      - ''
      - '&aClique para ver os eventos que participou!'
    clanLore:
      - '&fSeus pontos: &e%pontos%'
      - '&fSeu clan: &e%clan%'
      - ''
      - '%info%'
      - ''
      - '&aClique para ver os eventos que participou!'
  ranking:
    name: "&a%clan% &6(#%position%)"
    lore:
      - '&fPontos: &e%pontos%'
      - '&fParticipações em eventos: &e%participacoes%'
  historic:
    name: "&a%event% &8(#%id%)"
    lore:
      - '&fData: &e%data%'
      - '&fPontos: &e%pontos%'
      - ''
      - '&fClan vencedor: &e%clan%'
      - '&fJogadores do clan: &e%players%'
  period:
    material: "SUNFLOWER"
    name: "&6Selecionar período"
    lore:
      - '&7Selecione o período que deseja ver'
      - ''
      - '%info%'
      - ''
      - '&aClique para mudar o período.'
  sortRanking:
    material: "HOPPER"
    name: "&6Filtrar eventos"
    lore:
      - '&7Selecione o evento que deseja ver'
      - ''
      - '%info%'
      - ''
      - '&aClique para mudar o evento.'

webhook:
  title: "SAINT LIGA - %clan% <a:1Espada:1149729957434634403>"
  description: "O clã %clan% ganhou %pontos% pontos por %motivo%."
  footer: "Que a vitória seja dos mais fortes! Rede Saint"
  color: "16711680"
  fields:
    clan: "CLAN||%clan%"
    points: "PONTOS||%pontos%"
    motivo: "MOTIVO||%motivo%"
    mensal: "PONTUAÇÃO MENSAL||%mensal-points% pontos - #%mensal-position%º"
    trimestral: "PONTUAÇÃO TRIMESTRAL||%trimestral-points% pontos - #%trimestral-position%º"

# Sistema para premiar mensalmente o top clan (1º 2º e 3º lugar)
auto-reward:
  # Placeholders: $clanTag $player
  # Os comandos vão ser executado para cada jogador do clan
  MENSAL:
    1:
      - 'money give $player 1'
    2:
      - 'money give $player 1'
    3:
      - 'money give $player 1'
  TRIMESTRAL:
    1:
      - 'money give $player 1'
    2:
      - 'money give $player 1'
    3:
      - 'money give $player 1'

reward-per-event:
  Vote:
    name: "Votar"
    points: 1
  DragonSlayer:
    name: "Dragon Slayer"
    points: 15
  TitansBattle:
    gladiador:
      name: "Gladiador" # não sei qual nome colocar xd
      points: 15
    killer:
      name: "Killer"
      points: 10
  yEvents:
    BOLAO:
      name: "Bolão"
      points: 3
    CORRIDA:
      name: "Corrida"
      points: 3
    FASTCLICK:
      name: "FastClick"
      points: 3
    FIGHT:
      name: "Fight"
      points: 3
    KILLER:
      name: "Killer"
      points: 3
    LABIRINTO:
      name: "Labirinto"
      points: 3
    LOTERIA:
      name: "Loteria"
      points: 3
    MATEMATICA:
      name: "Matemática"
      points: 3
    PAINTBALL:
      name: "Paintball"
      points: 3
    PALAVRA:
      name: "Palavra"
      points: 3
    PARKOUR:
      name: "Parkour"
      points: 3
    QUIZ:
      name: "Quiz"
      points: 3
    SPLEEF:
      name: "Spleef"
      points: 3
    SUMO:
      name: "Sumo"
      points: 3
    RESTAUM:
      name: "RestaUm"
      points: 3
    FASTCRAFT:
      name: "FastCraft"
      points: 3


top-locations: [ ]