database:
  type: "sqlite"
  mysql:
    address: ""
    database: ""
    username: ""
    password: ""
  sqlite:
    file: "database.db"

# Sistema para premiar mensalmente o top clan (1ยบ 2ยบ e 3ยบ lugar)
auto-reward-top:
  day: 7
  hour: 13
  minute: 0

top-locations: []